---
- name: Fill service definition template
  ansible.builtin.template:
    src: "sustained.service"
    dest: "/etc/systemd/system/{{ pyservice_name }}-{{ item.name }}.service"
  loop: "{{ pyservice_services }}"

- name: Fill timer unit definition template
  ansible.builtin.template:
    src: "recurrent.service"
    dest: "/etc/systemd/system/{{ pyservice_name }}-{{ item.name }}.service"
  loop: "{{ pyservice_timers }}"

- name: Fill timer definition template
  ansible.builtin.template:
    src: "recurrent.timer"
    dest: "/etc/systemd/system/{{ pyservice_name }}-{{ item.name }}.timer"
  loop: "{{ pyservice_timers }}"

- name: Reload daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart services
  become: true
  ansible.builtin.systemd:
    name: "{{ pyservice_name }}-{{ item.name }}.service"
    state: restarted
  loop:
    "{{ pyservice_services }}"

- name: Enable timers
  become: true
  ansible.builtin.systemd:
    name: "{{ pyservice_name }}-{{ item.name }}.timer"
    state: restarted
  loop:
    "{{ pyservice_timers }}"
