---
- name: "Ensure directory"
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    owner: "{{ pyservice_user }}"
    group: "{{ pyservice_group }}"
    mode: "0700"
  when: "item.content != None"
  loop: "{{ pyservice_files }}"
  loop_control:
    label: "{{ item.dest }}"

- name: Populate necessary files
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ pyservice_user }}"
    group: "{{ pyservice_group }}"
    mode: "{{ item.mode | default('0600') }}"
  when: "item.content != None"
  loop: "{{ pyservice_files }}"
  loop_control:
    label: "{{ item.dest }}"
  no_log: true
