---
- name: List services
  register: pyservice_services_existing
  ansible.builtin.find:
    paths:
      - "/etc/systemd/system"
    pattern:
      - "{{ pyservice_name }}-*"

- name: Pause and disable services
  ansible.builtin.systemd:
    name: "{{ item.path | basename }}"
    enabled: false
    state: stopped
  loop:
    "{{ pyservice_services_existing.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Remove existing service files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ pyservice_services_existing.files }}"
  loop_control:
    label: "{{ item.path }}"
