---
- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - git
      - wget
    state: present

- name: Install uv
  ansible.builtin.script: install-uv.sh {{ uv_location }} {{ uv_version }}
  args:
    creates: "{{ uv_location }}/uv"

- name: Set up correct uv version
  ansible.builtin.command:
    cmd: "uv self update {{ uv_version }}"

- name: Copy SSH key
  when: "app_ssh_key"
  ansible.builtin.copy:
    content: "{{ app_ssh_key }}"
    dest: "{{ app_ssh_key_path }}"
    owner: "{{ app_user }}"
    mode: "0600"
  no_log: true

- name: Checkout the code
  ansible.builtin.git:
    repo: "{{ app_repo }}"
    dest: "{{ app_code_dir }}"
    version: "{{ app_tag }}"
    accept_hostkey: yes
    key_file: "{{ app_ssh_key_path }}"

- name: Sync dependencies
  ansible.builtin.command:
    cmd: "uv sync --locked --directory {{ app_code_dir }}"
