---
- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - git
      - wget
    state: present

- name: Install uv
  ansible.builtin.script: install-uv.sh {{ uv_location }} {{ uv_version }}
  args:
    creates: "{{ uv_location }}/uv"

- name: Set up correct uv version
  ansible.builtin.command:
    cmd: "{{ uv_bin }} self update {{ uv_version }}"

- name: Copy SSH key
  when: "pyservice_ssh_key"
  ansible.builtin.copy:
    content: "{{ pyservice_ssh_key }}"
    dest: "{{ pyservice_ssh_key_path }}"
    owner: "{{ pyservice_user }}"
    mode: "0600"
  no_log: true

- name: Checkout the code
  ansible.builtin.git:
    repo: "{{ pyservice_repo }}"
    dest: "{{ pyservice_code_dir }}"
    version: "{{ pyservice_tag }}"
    accept_hostkey: yes
    key_file: "{{ pyservice_ssh_key_path }}"
