---
- name: Ensure user
  become: true
  when: pyservice_ensure_user
  ansible.builtin.user:
    name: "{{ pyservice_user }}"
    comment: "User for {{ pyservice_name }} service"

- name: Ensure group
  become: true
  when: "pyservice_ensure_user and pyservice_group != pyservice_user"
  ansible.builtin.user:
    name: "{{ pyservice_user }}"
    groups:
    - "{{ pyservice_group }}"

- name: Create the app directory
  ansible.builtin.file:
    path: "{{ pyservice_root }}"
    state: directory
    mode: "0775"
    owner: "{{ pyservice_user }}"
    group: "{{ pyservice_group }}"

- name: Create the data directory
  ansible.builtin.file:
    path: "{{ pyservice_data_dir }}"
    state: directory
    mode: "0750"
    owner: "{{ pyservice_user }}"
    group: "{{ pyservice_group }}"

- name: Create the app directory
  ansible.builtin.file:
    path: "{{ pyservice_dir }}"
    state: directory
    mode: "0775"
    owner: "{{ pyservice_user }}"
    group: "{{ pyservice_group }}"

- name: Create the config directory
  ansible.builtin.file:
    path: "{{ pyservice_config_dir }}"
    state: directory
    mode: "0750"
    owner: "{{ pyservice_user }}"
    group: "{{ pyservice_group }}"
